Update for opening nominations
numfocus/elections pull request #15
Opened 2024-06-14 16:11 UTC by pavithraes

The following are updated:

* Board responsibilities
* Election process - Soliciting nominations
* Timeline

2024-06-14 17:06 UTC, tkoyama010 requested changes

2024-06-14 17:06 UTC, tkoyama010 commented on election-process.md
> +Nominees for the **Technical Steering Committee** should be contributors or members of a NumFOCUS Sponsored or Affiliated Project community. They should have experience in areas such as governance or
```suggestion
Nominees for the **Technical Steering Committee** should be contributors or members of a NumFOCUS Sponsored or Affiliated Project community.
They should have experience in areas such as governance or community leadership, budget creation and management, infrastructure, and strategic planning.
```

2024-06-14 17:09 UTC, tkoyama010 commented
pre-commit.ci autofix

2024-06-14 17:11 UTC, lsilen commented on board-responsibilities.md
>  ## Board of Directors - Administrative or Executive Branch
Delete Executive Branch and use Administrative Board to be consistent with what the board is using.

2024-06-14 17:45 UTC, pavithraes commented
Thanks for the comments! This PR was also reviewed during the election committee meting, so I'll take the liberty to self-merge. :)

2024-06-14 17:46 UTC, merged

2024-06-30 01:10 UTC, tkoyama010 commented
@all-contributors please add @lsilen for review